apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeinvaders-cert  #name of this object
  namespace: kubeinvaders #same namespace as deployment of ingress
spec:
  dnsNames:
    - www.killpods.ga
  secretName: kubeinvaders-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer